purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7022602646611631
  brandStrength: 1
  lightness: 0.04792519798502326
  brandColors:
    - '#3F3E3C'
    - '#1E1A19'
    - '#C8C0BE'
    - '#E86D27'
    - '#A94B13'
  rhythmicContrast: 0.3235222599469125
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 419Creative
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4731471
layout_spectrum: 0
